--- #YAML:1.0
name:               SOOT-App
version:            0.03
abstract:           A Perl REPL using SOOT (ROOT)
author:
    - Steffen Mueller <smueller@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Capture::Tiny:  0
    Devel::REPL:    1.003000
    SOOT:           0.04
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
